version: "3.4"

services:
  postgresql:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./databases/postgresql:/var/lib/postgresql/data
    environment:
      # - POSTGRES_USER=admin # default POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@postgres.com
      - PGADMIN_DEFAULT_PASSWORD=admin
